export const categories = [
  { id: "all", name: "كل المنتجات" },
  { id: "socks", name: "شرابات" },
  { id: "scarves", name: "كوفيات" },
  { id: "gloves", name: "جوانتيات" },
  { id: "jackets", name: "جواكت تريكو وكروشيه" },
  { id: "sweaters", name: "بلوفرات تريكو وكروشيه" },
  { id: "kids", name: "سالوبيت اطفال" },
  { id: "hats", name: "أيس كاب وقبعات" },
  { id: "blankets", name: "بطانيات كروشيه" }
];

export const products = [
  {
    id: "p1",
    name: "بلوفر صوف ألباكا تريكو",
    price: 850,
    category: "sweaters",
    colors: ["ivory", "sage", "rose"],
    sizes: ["S", "M", "L", "XL"],
    description: "بلوفر تريكو يدوي الصنع من صوف الألباكا الممتاز. ناعم جداً ودافئ ومريح.",
    inStock: true,
    featured: true,
    images: ["/products/WhatsApp Image 2026-05-06 at 10.39.44 PM (1).jpeg"],
    imageFileName: "WhatsApp Image 2026-05-06 at 10.39.44 PM (1).jpeg"
  },
  {
    id: "p2",
    name: "جاكيت كروشيه مربعات الجدة",
    price: 950,
    category: "jackets",
    colors: ["lavender", "sage", "sand"],
    sizes: ["M", "L", "XL"],
    description: "جاكيت بستايل الجراني سكوير الكلاسيكي، ألوان باستيل هادئة ومريحة.",
    inStock: true,
    featured: true,
    images: ["/products/WhatsApp Image 2026-05-06 at 10.39.44 PM (2).jpeg"],
    imageFileName: "WhatsApp Image 2026-05-06 at 10.39.44 PM (2).jpeg"
  },
  {
    id: "p3",
    name: "كوفية تريكو غرزة كبيرة",
    price: 350,
    category: "scarves",
    colors: ["rose", "sand", "sage"],
    sizes: ["One Size"],
    description: "كوفية تريكو طويلة ودافئة، مصنوعة من مزيج صوف ناعم لا يسبب الحساسية.",
    inStock: true,
    featured: false,
    images: ["/products/WhatsApp Image 2026-05-06 at 10.39.44 PM (3).jpeg"],
    imageFileName: "WhatsApp Image 2026-05-06 at 10.39.44 PM (3).jpeg"
  },
  {
    id: "p4",
    name: "سالوبيت أطفال وحذاء مطابق",
    price: 600,
    category: "kids",
    colors: ["peach", "sage", "ivory"],
    sizes: ["0-3M", "3-6M", "6-12M"],
    description: "طقم رائع ومريح للأطفال بلمسات يدوية دقيقة.",
    inStock: true,
    featured: true,
    images: ["/products/WhatsApp Image 2026-05-06 at 10.39.44 PM (4).jpeg"],
    imageFileName: "WhatsApp Image 2026-05-06 at 10.39.44 PM (4).jpeg"
  },
  {
    id: "p5",
    name: "بلوفر كروشيه صيفي مفرغ",
    price: 550,
    category: "sweaters",
    colors: ["sand", "ivory", "lavender"],
    sizes: ["S", "M", "L"],
    description: "بلوفر كروشيه بخيوط قطنية ناعمة، تصميم مفرغ وعصري.",
    inStock: true,
    featured: false,
    images: ["/products/WhatsApp Image 2026-05-06 at 10.39.44 PM (5).jpeg"],
    imageFileName: "WhatsApp Image 2026-05-06 at 10.39.44 PM (5).jpeg"
  },
  {
    id: "p6",
    name: "جوانتي صوف بدون أصابع",
    price: 150,
    category: "gloves",
    colors: ["sage", "rose"],
    sizes: ["One Size"],
    description: "جوانتي تريكو شتوي للتدفئة مع حرية حركة الأصابع.",
    inStock: true,
    featured: false,
    images: ["/products/WhatsApp Image 2026-05-06 at 10.39.44 PM (6).jpeg"],
    imageFileName: "WhatsApp Image 2026-05-06 at 10.39.44 PM (6).jpeg"
  },
  {
    id: "p7",
    name: "شرابات شتوية ثقيلة للبيت",
    price: 120,
    category: "socks",
    colors: ["ivory", "peach"],
    sizes: ["One Size"],
    description: "شرابات كروشيه بتصميم دافئ جداً ومريح للقدمين في أيام الشتاء الباردة.",
    inStock: true,
    featured: true,
    images: ["/products/WhatsApp Image 2026-05-06 at 10.39.44 PM (7).jpeg"],
    imageFileName: "WhatsApp Image 2026-05-06 at 10.39.44 PM (7).jpeg"
  },
  {
    id: "p8",
    name: "كارديجان حلم اللافندر",
    price: 750,
    category: "jackets",
    colors: ["lavender", "ivory"],
    sizes: ["M", "L"],
    description: "كارديجان كروشيه ناعم بأكمام واسعة وأزرار خشبية. يضفي لمسة ربيعية دافئة.",
    inStock: true,
    featured: true,
    images: ["/products/WhatsApp Image 2026-05-06 at 10.39.44 PM (8).jpeg"],
    imageFileName: "WhatsApp Image 2026-05-06 at 10.39.44 PM (8).jpeg"
  },
  {
    id: "p9",
    name: "أيس كاب تريكو بوم بوم",
    price: 180,
    category: "hats",
    colors: ["rose", "ivory"],
    sizes: ["One Size"],
    description: "أيس كاب تريكو يدوي مع كرة فرو ناعمة، تدفئة مثالية للأذنين.",
    inStock: true,
    featured: false,
    images: ["/products/WhatsApp Image 2026-05-08 at 1.03.48 AM.jpeg"],
    imageFileName: "WhatsApp Image 2026-05-08 at 1.03.48 AM.jpeg"
  },
  {
    id: "p10",
    name: "بطانية كروشيه للأطفال",
    price: 1200,
    category: "blankets",
    colors: ["sage", "ivory", "peach"],
    sizes: ["90x90cm"],
    description: "بطانية كروشيه يدوية فائقة النعومة، مثالية لسرير الطفل أو العربة.",
    inStock: true,
    featured: true,
    images: ["/products/WhatsApp Image 2026-05-08 at 1.03.49 AM (1).jpeg"],
    imageFileName: "WhatsApp Image 2026-05-08 at 1.03.49 AM (1).jpeg"
  },
  {
    id: "p11",
    name: "طقم سالوبيت أزرق سماوي",
    price: 650,
    category: "kids",
    colors: ["blue", "ivory"],
    sizes: ["0-3M", "3-6M"],
    description: "سالوبيت تريكو ناعم مع قبعة مطابقة، تصميم كلاسيكي دافئ.",
    inStock: true,
    featured: false,
    images: ["/products/WhatsApp Image 2026-05-08 at 1.03.49 AM (2).jpeg"],
    imageFileName: "WhatsApp Image 2026-05-08 at 1.03.49 AM (2).jpeg"
  },
  {
    id: "p12",
    name: "كوفية صوف عريضة",
    price: 380,
    category: "scarves",
    colors: ["sand", "charcoal"],
    sizes: ["One Size"],
    description: "كوفية تريكو بغرزة ضيقة لتدفئة مضاعفة في الأيام شديدة البرودة.",
    inStock: true,
    featured: false,
    images: ["/products/WhatsApp Image 2026-05-08 at 1.03.49 AM (3).jpeg"],
    imageFileName: "WhatsApp Image 2026-05-08 at 1.03.49 AM (3).jpeg"
  },
  {
    id: "p13",
    name: "جاكيت تريكو أزرار جانبية",
    price: 880,
    category: "jackets",
    colors: ["sage", "sand"],
    sizes: ["S", "M", "L"],
    description: "جاكيت تريكو بتصميم عصري مع أزرار جانبية خشبية، أنيق ودافئ.",
    inStock: true,
    featured: false,
    images: ["/products/WhatsApp Image 2026-05-08 at 1.03.49 AM (4).jpeg"],
    imageFileName: "WhatsApp Image 2026-05-08 at 1.03.49 AM (4).jpeg"
  },
  {
    id: "p14",
    name: "بلوفر كروشيه ملون",
    price: 720,
    category: "sweaters",
    colors: ["multi"],
    sizes: ["M", "L"],
    description: "بلوفر كروشيه يدوي بألوان متداخلة تضفي حيوية على إطلالتك الشتوية.",
    inStock: true,
    featured: true,
    images: ["/products/WhatsApp Image 2026-05-08 at 1.03.49 AM (5).jpeg"],
    imageFileName: "WhatsApp Image 2026-05-08 at 1.03.49 AM (5).jpeg"
  }
];

export const mockUser = {
  id: "u1",
  name: "سارة م.",
  email: "sarah@example.com",
  role: "admin",
  orders: 4,
  joined: "2024-01-15"
};
